package com.icei.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.icei.domain.Admin;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int deleteByPrimaryKey(Integer adminId);

    /**
     * 根据用户名查询用户信息
     * @param adminCode
     * @return
     */
    Admin selectByName(@Param("adminCode") String adminCode);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    Admin selectByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKey(Admin record);
    
    int getResultsCount(@Param("keyword")String keyword,@Param("searchType")String searchType);
    
    List<Admin> getTargetResult(@Param("start")Integer start,@Param("end")Integer end,@Param("keyword")String keyword,@Param("searchType")String searchType);

    int updateRoleIdByAdminId(@Param("adminId")Integer adminId,@Param("targetRoleId")Integer targetRoleId);
}